'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HolaMundoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HolaMundo", ReplyAction:="*")>  _
        Function HolaMundo(ByVal request As ServiceReference1.HolaMundoRequest) As ServiceReference1.HolaMundoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HolaMundo", ReplyAction:="*")>  _
        Function HolaMundoAsync(ByVal request As ServiceReference1.HolaMundoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.HolaMundoResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Sumar", ReplyAction:="*")>  _
        Function Sumar(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Sumar", ReplyAction:="*")>  _
        Function SumarAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Fact", ReplyAction:="*")>  _
        Function Fact(ByVal nro As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Fact", ReplyAction:="*")>  _
        Function FactAsync(ByVal nro As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function Resta(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function RestaAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicar", ReplyAction:="*")>  _
        Function Multiplicar(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicar", ReplyAction:="*")>  _
        Function MultiplicarAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Dividir", ReplyAction:="*")>  _
        Function Dividir(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Dividir", ReplyAction:="*")>  _
        Function DividirAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Potencia", ReplyAction:="*")>  _
        Function Potencia(ByVal bas As Integer, ByVal exp As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Potencia", ReplyAction:="*")>  _
        Function PotenciaAsync(ByVal bas As Integer, ByVal exp As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function Seno(ByVal nro As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function SenoAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Coseno", ReplyAction:="*")>  _
        Function Coseno(ByVal nro As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Coseno", ReplyAction:="*")>  _
        Function CosenoAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Tangente", ReplyAction:="*")>  _
        Function Tangente(ByVal nro As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Tangente", ReplyAction:="*")>  _
        Function TangenteAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Inverso", ReplyAction:="*")>  _
        Function Inverso(ByVal nro As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Inverso", ReplyAction:="*")>  _
        Function InversoAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HolaMundoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HolaMundo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.HolaMundoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.HolaMundoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HolaMundoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HolaMundoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HolaMundoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.HolaMundoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.HolaMundoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HolaMundoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HolaMundoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HolaMundoResult As String)
            MyBase.New
            Me.HolaMundoResult = HolaMundoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_HolaMundo(ByVal request As ServiceReference1.HolaMundoRequest) As ServiceReference1.HolaMundoResponse Implements ServiceReference1.WebService1Soap.HolaMundo
            Return MyBase.Channel.HolaMundo(request)
        End Function
        
        Public Function HolaMundo() As String
            Dim inValue As ServiceReference1.HolaMundoRequest = New ServiceReference1.HolaMundoRequest()
            inValue.Body = New ServiceReference1.HolaMundoRequestBody()
            Dim retVal As ServiceReference1.HolaMundoResponse = CType(Me,ServiceReference1.WebService1Soap).HolaMundo(inValue)
            Return retVal.Body.HolaMundoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_WebService1Soap_HolaMundoAsync(ByVal request As ServiceReference1.HolaMundoRequest) As System.Threading.Tasks.Task(Of ServiceReference1.HolaMundoResponse) Implements ServiceReference1.WebService1Soap.HolaMundoAsync
            Return MyBase.Channel.HolaMundoAsync(request)
        End Function
        
        Public Function HolaMundoAsync() As System.Threading.Tasks.Task(Of ServiceReference1.HolaMundoResponse)
            Dim inValue As ServiceReference1.HolaMundoRequest = New ServiceReference1.HolaMundoRequest()
            inValue.Body = New ServiceReference1.HolaMundoRequestBody()
            Return CType(Me,ServiceReference1.WebService1Soap).HolaMundoAsync(inValue)
        End Function
        
        Public Function Sumar(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.Sumar
            Return MyBase.Channel.Sumar(nro1, nro2)
        End Function
        
        Public Function SumarAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.SumarAsync
            Return MyBase.Channel.SumarAsync(nro1, nro2)
        End Function
        
        Public Function Fact(ByVal nro As Integer) As Double Implements ServiceReference1.WebService1Soap.Fact
            Return MyBase.Channel.Fact(nro)
        End Function
        
        Public Function FactAsync(ByVal nro As Integer) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.FactAsync
            Return MyBase.Channel.FactAsync(nro)
        End Function
        
        Public Function Resta(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.Resta
            Return MyBase.Channel.Resta(nro1, nro2)
        End Function
        
        Public Function RestaAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.RestaAsync
            Return MyBase.Channel.RestaAsync(nro1, nro2)
        End Function
        
        Public Function Multiplicar(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.Multiplicar
            Return MyBase.Channel.Multiplicar(nro1, nro2)
        End Function
        
        Public Function MultiplicarAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.MultiplicarAsync
            Return MyBase.Channel.MultiplicarAsync(nro1, nro2)
        End Function
        
        Public Function Dividir(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.Dividir
            Return MyBase.Channel.Dividir(nro1, nro2)
        End Function
        
        Public Function DividirAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.DividirAsync
            Return MyBase.Channel.DividirAsync(nro1, nro2)
        End Function
        
        Public Function Potencia(ByVal bas As Integer, ByVal exp As Integer) As Double Implements ServiceReference1.WebService1Soap.Potencia
            Return MyBase.Channel.Potencia(bas, exp)
        End Function
        
        Public Function PotenciaAsync(ByVal bas As Integer, ByVal exp As Integer) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.PotenciaAsync
            Return MyBase.Channel.PotenciaAsync(bas, exp)
        End Function
        
        Public Function Seno(ByVal nro As Double) As Double Implements ServiceReference1.WebService1Soap.Seno
            Return MyBase.Channel.Seno(nro)
        End Function
        
        Public Function SenoAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.SenoAsync
            Return MyBase.Channel.SenoAsync(nro)
        End Function
        
        Public Function Coseno(ByVal nro As Double) As Double Implements ServiceReference1.WebService1Soap.Coseno
            Return MyBase.Channel.Coseno(nro)
        End Function
        
        Public Function CosenoAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.CosenoAsync
            Return MyBase.Channel.CosenoAsync(nro)
        End Function
        
        Public Function Tangente(ByVal nro As Double) As Double Implements ServiceReference1.WebService1Soap.Tangente
            Return MyBase.Channel.Tangente(nro)
        End Function
        
        Public Function TangenteAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.TangenteAsync
            Return MyBase.Channel.TangenteAsync(nro)
        End Function
        
        Public Function Inverso(ByVal nro As Double) As Double Implements ServiceReference1.WebService1Soap.Inverso
            Return MyBase.Channel.Inverso(nro)
        End Function
        
        Public Function InversoAsync(ByVal nro As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.InversoAsync
            Return MyBase.Channel.InversoAsync(nro)
        End Function
    End Class
End Namespace
